site_name: LiteGeometry
site_url: https://LiteGeometry.github.io
repo_url: https://github.com/ZhikangLai/LiteGeometry
site_author: Zhikang Lai
repo_name: GitHub


nav:
  - Home: index.md

  - Examples and Tutorials: examples.md


theme: 
  name: material
  font:
    text: Roboto
    code: Consolas

  favicon: icon/favicon.png
  logo: icon/favicon.png

  palette: 
    primary: blue 
    accent: teal  

  features:
    - content.code.copy 
    - content.tabs.link
    - content.code.annotate
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.footer 

  highlightjs: false

copyright: Copyright &copy; 2025 Zhikang Lai. All Rights Reserved.

markdown_extensions: 
  - pymdownx.highlight:
      pygments_style: monokai
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhikangLai
      name: Zhikang Lai